In [1]:
import numpy as np
import tensorflow as tf

In [3]:
#Frobenious Norm
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [4]:
np.linalg.norm(x)

5.477225575051661

In [5]:
(1**2 + 2**2 + 3**2 + 4**2 )**(1/2)

5.477225575051661

In [10]:
x_tf = tf.Variable([[1,2],[3,4.]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [11]:
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.dot(A,x)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [21]:
m1 = np.array([[3,4],[5,6],[7,8]])
m2 = np.array([1,2])

In [22]:
np.dot(m1,m2)

array([11, 17, 23])

In [23]:
m1_tf = tf.Variable([[3,4],[5,6],[7,8]])
m2_tf = tf.Variable([1,2])

In [24]:
tf.linalg.matvec(m1_tf,m2_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

In [25]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
B = np.array([[2,3],[5,8]])
B

array([[2, 3],
       [5, 8]])

In [31]:
np.dot(A,B)

array([[12, 19],
       [26, 41],
       [40, 63]])

In [35]:
A_tf = tf.convert_to_tensor(A,dtype=tf.int32)
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [37]:
B_tf = tf.convert_to_tensor(B,dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 8]])>

In [38]:
tf.matmul(A_tf,B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 19],
       [26, 41],
       [40, 63]])>

In [39]:
#Symmetric matrix
X = np.array([[0,1,2],[1,7,8],[2,8,9]])

In [40]:
X.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [41]:
X==X.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
#Identity Matrix
ind = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
ind

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
new = np.array([34,56,25,7])
new

array([34, 56, 25,  7])

In [47]:
np.dot(ind,new)

array([34, 56, 25,  7])

In [48]:
#y=wx
#x^-1*y = w*x^-1*x
#w = x^-1*y

In [52]:
x
x = np.linalg.inv(x)
x

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
xp = np.array([[4,2],[-5,-3]])
xp

array([[ 4,  2],
       [-5, -3]])

In [3]:
x = np.linalg.inv(x)
x

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [5]:
y = np.array([4,-7])
y

array([ 4, -7])

In [7]:
w = np.dot(x,y)
w
# w = (x^-1)*y 

array([-1.,  4.])

In [10]:
np.dot(xp,w)
#y==np.dot(xp,w)

array([ 4., -7.])

In [11]:
#inversion in tensorflow
tf.linalg.inv(tf.Variable([[4,2],[-5,-3.]]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

In [12]:
#Error in matrix inversion: Singular Matrix
x = np.array([[-4,1],[-4,1]])
np.linalg.inv(x)

LinAlgError: Singular matrix

In [13]:
#Error in matrix inversion: Singular Matrix
y = np.array([[-4,1],[-8,2]])
np.linalg.inv(y)

LinAlgError: Singular matrix

In [21]:
#diagonal Matrix
x = np.array([4,5,7])
np.diag(x)
y = np.array([[8,9,6]])
np.diag(x)*y

array([[32,  0,  0],
       [ 0, 45,  0],
       [ 0,  0, 42]])

In [22]:
np.linalg.inv(np.diag(x))

array([[0.25      , 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.14285714]])

In [23]:
l = np.diag(np.array([1/4,1/5,1/7]))
l.T

array([[0.25      , 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.14285714]])

In [24]:
#so diag(x)^-1 == diag[1/x1,1/x2,.....,1/xn]^T

In [31]:
#Orthogonal Matrix 
#which consist of orthonormal vectors
I3 = np.diag(np.array([1,1,1]))
I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
#0th Column and 1st column of I3 are perpendicular to each other
np.dot(I3[:,0],I3[:,1])

0

In [27]:
#1st and 2nd column of I3 are perpendicular to each other
np.dot(I3[:,1],I3[:,2])

0

In [28]:
#0th and 2nd column of I3 are perpendicular to each other
np.dot(I3[:,0],I3[:,2])

0

In [29]:
#each column consist of vector which has unit norm
#Norm of the 0th column
np.linalg.norm(I3[:,0])

1.0

In [30]:
#Norm of the 1st column
np.linalg.norm(I3[:,1])

1.0

In [32]:
#Norm of the 2nd column 
np.linalg.norm(I3[:,2])

1.0

In [34]:
#Another example of orthogonal matrix
k = np.array([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])
k

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [35]:
np.dot(k[:,0],k[:,1])

0.0

In [37]:
np.dot(k[:,1],k[:,2])

0.0

In [38]:
np.dot(k[:,0],k[:,2])

0.0

In [39]:
np.linalg.norm(k[:,0])

1.0

In [40]:
np.linalg.norm(k[:,1])

1.0

In [41]:
np.linalg.norm(k[:,2])

1.0