# Welcome to NumPy practice

In [1]:
import numpy as np

In [9]:
myarr = np.array([[3,6,32,7]],np.int8)
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [12]:
myarr[0,0]

3

In [13]:
myarr.shape

(1, 4)

In [14]:
myarr.dtype

dtype('int8')

In [15]:
myarr[0,1] = 45

In [16]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

# Array Creation: Conversion from other Python Structures

In [17]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [18]:
listarray.dtype

dtype('int32')

In [19]:
listarray.size

9

In [20]:
listarray.shape

(3, 3)

# Array Creation: Intrinsic numpy array creation objects (e.g., arange,ones,zeros,etc.)

In [22]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zeros.shape

(2, 5)

In [24]:
zeros.dtype

dtype('float64')

In [25]:
zeros.size

10

In [26]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace1 = np.linspace(1,50,10)
lspace1

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
lspace2 = np.linspace(1,4,4)
lspace2

array([1., 2., 3., 4.])

In [31]:
lspace3 = np.linspace(1,5,4)
lspace3

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [32]:
emp = np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 5.56295287e-307,
        4.22788818e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        1.37961302e-306, 1.42410974e-306, 2.22522596e-306]])

In [33]:
emp_like = np.empty_like(lspace2)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [34]:
#Indentity Matrix
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
ide.shape

(45, 45)

In [36]:
arr =  np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr = arr.reshape(3,33)

In [38]:
arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

In [45]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0) #row wise sum

array([12,  8,  9])

In [49]:
ar.sum(axis=1) #column wise sum

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim

2

In [54]:
ar.size #these are the attributes

9

In [56]:
ar.nbytes  #total bytes consumed

36

In [57]:
one = np.array([1,3,4,634,2])
one

array([  1,   3,   4, 634,   2])

In [60]:
one.argmax()  #method #It provides the index where the maximum element is present

3

In [61]:
one.argmin()

0

In [62]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [66]:
ar.argmin()

8

In [67]:
ar.argmax()

6

In [68]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [69]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [70]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
arnew = np.array([[1,2,3],[4,5,6],[0,1,7]])
arnew

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [73]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [75]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [78]:
[674,89] + [67,9]

[674, 89, 67, 9]

In [80]:
ar * ar2  # Hadamard Multiplication

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [83]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [84]:
ar.sum()

29

In [85]:
ar.max()

7

In [86]:
ar.min()

0

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
type(np.where(ar>5))

tuple

In [90]:
np.count_nonzero(ar)

8

In [91]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [92]:
ar[1,1] = 0

In [93]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [94]:
import sys

In [96]:
py_ar = [0,4,55,2]

In [97]:
np_ar = np.array(py_ar)

In [99]:
sys.getsizeof(1) * len(py_ar)

112

In [100]:
np_ar.itemsize * np_ar.size

16

In [102]:
np_ar.tolist()

[0, 4, 55, 2]