<a href="https://colab.research.google.com/github/Koyelisha/Mathematics/blob/main/Point_wise_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch

In [27]:
xs = torch.tensor([0,1,2,3,4,5,6,7.])
xs

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [28]:
ys = torch.tensor([1.86,1.31,0.62,.33,.09,-.67,-1.23,-1.37])
ys

tensor([ 1.8600,  1.3100,  0.6200,  0.3300,  0.0900, -0.6700, -1.2300, -1.3700])

In [29]:
def regression(my_x,my_m,my_b):
  return my_x*my_m + my_b

In [30]:
i=6
x=xs[i]
y=ys[i]

In [31]:
x

tensor(6.)

In [32]:
y

tensor(-1.2300)

In [33]:
m = torch.tensor([0.9]).requires_grad_()
m

tensor([0.9000], requires_grad=True)

In [34]:
b = torch.tensor([0.1]).requires_grad_()
b

tensor([0.1000], requires_grad=True)

In [35]:
yhat = regression(x,m,b)
yhat

tensor([5.5000], grad_fn=<AddBackward0>)

In [36]:
def mse(yhat,y):
  return (yhat-y)**2

In [37]:
C = mse(yhat,y)
C

tensor([45.2929], grad_fn=<PowBackward0>)

In [38]:
C.backward

<bound method Tensor.backward of tensor([45.2929], grad_fn=<PowBackward0>)>

In [39]:
m.grad

In [40]:
b.grad

In [41]:
delcdelm = 2*x*(yhat-y)
delcdelm

tensor([80.7600], grad_fn=<MulBackward0>)

In [42]:
delcdelb = 2*(yhat-y)
delcdelb

tensor([13.4600], grad_fn=<MulBackward0>)

In [44]:
nablac = torch.tensor([[delcdelm,delcdelb]]).T
nablac

tensor([[80.7600],
        [13.4600]])