In [1]:
import numpy as np
import tensorflow as tf

In [3]:
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
x.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [7]:
x_tf = tf.Variable([[25,2],[5,26],[3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [11]:
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [12]:
x=x+2
x

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [13]:
x*2

array([[54,  8],
       [14, 56],
       [10, 18]])

In [14]:
x

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [16]:
(x_tf + 2)*2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[54,  8],
       [14, 56],
       [10, 18]])>

In [17]:
tf.add(tf.multiply(x_tf,2),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [18]:
x

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [19]:
a = x + 2
a

array([[29,  6],
       [ 9, 30],
       [ 7, 11]])

In [20]:
#Hadamard or element wise multiplication
x * a

array([[783,  24],
       [ 63, 840],
       [ 35,  99]])

In [21]:
a + x

array([[56, 10],
       [16, 58],
       [12, 20]])

In [22]:
a_tf = x_tf + 2

In [23]:
x_tf + a_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [24]:
x_tf * a_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]])>

In [25]:
x.sum()

80

In [26]:
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [27]:
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [30]:
x.sum(axis=0) #row wise sum
x.sum(axis=1) #column wise sum

array([31, 35, 14])

In [29]:
tf.reduce_sum(x_tf,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10])>

In [31]:
x.max(axis=0)

array([27, 28])

In [32]:
x

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [33]:
x.min(axis=1)

array([4, 7, 5])

In [34]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [35]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [36]:
25*1 + 2*2 + 5*3

44

In [38]:
np.dot(x,y)

44

In [39]:
x_tf = tf.Variable([25,2,5])
y_tf = tf.Variable([1,2,3])

In [40]:
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [41]:
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [45]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [46]:
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [47]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [48]:
y = np.array([[42,4,7,99],[-99,-3,17,22]])
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [49]:
y = y.T

In [50]:
y

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [51]:
a = np.array([[25,10],[-2,1]])
b = np.array([[-1,7],[10,8]])

In [52]:
a*b

array([[-25,  70],
       [-20,   8]])

In [53]:
w = np.array([-1,2,-2])
x = np.array([5,10,0])

In [55]:
np.dot(w,x)

15